### PR TITLE
Drop Node 0.10 and 0.12

### PR DESCRIPTION
**Pull request by feross**
Remove 3 unneeded dependencies!

### CODE REVIEW

**Comment by SamVerschueren** [comment]
This is not enough... You have to use all the ES2015 features as well like const, let, fat arrow, ...

**Comment by feross** [comment]
I know that Sindre loves his fat arrows! But that can happen in another PR.

I normally wouldn't send a PR like this, but I'm trying to reduce the
startup time of my Electron app, WebTorrent Desktop, and reducing JS parse
time is a huge win. We recently got startup under 1s!

**Comment by schnittstabil** [comment]
Though, personally, I don't mind to drop support for `v0.12` too, I also know its [LTS](https://github.com/nodejs/LTS) ends at 2016-12-31.

**Comment by sindresorhus** [comment]
Thanks @feross :)

**Comment by feross** [comment]
@sindresorhus Any chance you could do a release?

**Comment by sindresorhus** [comment]
Done

**Pull request merged**
